### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [1]:
for num in range(60, 70):
    print(num)
    
#raise NotImplementedError()

60
61
62
63
64
65
66
67
68
69


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [2]:
import math

# Initialize variables to keep track of the sum, count, and sum of squared differences
total = 0
count = 0
squared_diff_sum = 0

while True:
    try:
        # Read a number from the user
        num = float(input("Enter a number (0 to stop): "))
        
        # Check if the number is 0 to exit the loop
        if num == 0:
            break
        
        # Update the total and count
        total += num
        count += 1
        
        # Update the sum of squared differences
        squared_diff_sum += (num ** 2)
    
    except ValueError:
        print("Invalid input. Please enter a valid number.")

# Calculate the mean
mean = total / count if count > 0 else 0

# Calculate the standard deviation
if count > 1:
    variance = (squared_diff_sum / count) - (mean ** 2)
    std_deviation = math.sqrt(variance)
else:
    std_deviation = 0

# Print the results
print(f"Mean: {mean}")
print(f"Standard Deviation: {std_deviation}")

#raise NotImplementedError()

Enter a number (0 to stop):  87
Enter a number (0 to stop):  23
Enter a number (0 to stop):  9
Enter a number (0 to stop):  0


Mean: 39.666666666666664
Standard Deviation: 33.95421754199159


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [3]:
l = [2, 3, -2, -7, 0, 2, 3]

for num in l:
    if num % 2 != 0:
        print(num)
        
#raise NotImplementedError()

3
-7
3


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [5]:
# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

# Function to get the first N prime numbers
def get_n_primes(N):
    if N <= 0:
        return []
    primes = []
    num = 2
    while len(primes) < N:
        if is_prime(num):
            primes.append(num)
        num += 1
    return primes
    
#raise NotImplementedError()

In [6]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [7]:
def get_nth_fibonacci(N):
    if N < 0:
        raise ValueError("N cannot be negative")
    elif N == 0:
        return 0
    elif N == 1:
        return 1
    else:
        a, b = 0, 1
        for _ in range(2, N + 1):
            a, b = b, a + b
        return b
        
#raise NotImplementedError()

In [8]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [9]:
# Function to filter a list based on a predicate
def filter_list(lst, predicate):
    return [x for x in lst if predicate(x)]

# Predicate function to check if a number is odd
def is_odd(x):
    return x % 2 != 0

# Predicate function to check if a number is prime
def is_prime(x):
    if x <= 1:
        return False
    if x <= 3:
        return True
    if x % 2 == 0 or x % 3 == 0:
        return False
    i = 5
    while i * i <= x:
        if x % i == 0 or x % (i + 2) == 0:
            return False
        i += 6
    return True
    
#raise NotImplementedError()

In [10]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [11]:
# Function to reduce a sequence using a two-argument function
def reduce(sequence, func, accumulator=None):
    if len(sequence) == 0:
        if accumulator is not None:
            return accumulator
        else:
            raise ValueError("Cannot reduce an empty sequence without an initial value.")
    elif len(sequence) == 1:
        if accumulator is not None:
            return func(accumulator, sequence[0])
        else:
            return sequence[0]
    else:
        if accumulator is not None:
            result = accumulator
        else:
            result = func(sequence[0], sequence[1])
            sequence = sequence[2:]
        for element in sequence:
            result = func(result, element)
        return result

# Function to add two numbers
def add(x, y):
    return x + y

# Function to multiply two numbers
def product(x, y):
    return x * y

# Function to concatenate two strings
def string_addition(x, y):
    return x + y

# Function to calculate the length and add it to an integer
def string_len_add(x, y):
    return x + len(y)
    
#raise NotImplementedError()

In [12]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [16]:
from functools import reduce

# Function to count odd elements in a list of integers
def count_odd(acc, num):
    return acc + (1 if num % 2 != 0 else 0)

# Function to find the maximum of a list of integers
def find_max(acc, num):
    return max(acc, num)

# Function to find the longest string in a list of strings
def find_longest(acc, string):
    return max(acc, string, key=len)
    
#raise NotImplementedError()

In [17]:
# List of integers
integers_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# List of strings
strings_list = ["apple", "banana", "cherry", "date"]

# Test a. Count the number of odd elements in a list of integers.
count_odd_result = reduce(count_odd, integers_list, 0)
print("Count of odd elements:", count_odd_result)

# Test b. Find the maximum of a list of integers.
max_int_result = reduce(find_max, integers_list)
print("Maximum integer:", max_int_result)

# Test c. Find the longest string in a list of strings.
longest_string_result = reduce(find_longest, strings_list)
print("Longest string:", longest_string_result)

#raise NotImplementedError()

Count of odd elements: 5
Maximum integer: 9
Longest string: banana


9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [18]:
import numpy as np

def pairwise_row_distance(matrix):
    # Convert the input list of lists into a NumPy array
    A = np.array(matrix)
    
    # Calculate the pairwise L2 distances using broadcasting
    num_rows = A.shape[0]
    pairwise_distances = np.zeros((num_rows, num_rows), dtype=float)
    
    for i in range(num_rows):
        for j in range(num_rows):
            pairwise_distances[i, j] = np.linalg.norm(A[i] - A[j])
    
    return pairwise_distances

# Function to check if the input is a matrix
def is_matrix(matrix):
    if isinstance(matrix, (list, np.ndarray)) and len(matrix) > 0 and all(isinstance(row, (list, np.ndarray)) for row in matrix):
        return True
    return False

# Function to transpose a matrix
def transpose(matrix):
    return list(map(list, zip(*matrix)))
    
#raise NotImplementedError()

In [ ]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [20]:
class A:
    def __init__(self, value):
        self.value = value

    def print_value(self):
        print(self.value)
        
#raise NotImplementedError()

In [21]:
a = A("abc")
a.print_value()

abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [22]:
class B:
    def __init__(self, public_value, private_value):
        self.this_is_public = public_value
        self.__this_is_private = private_value
        
# Access the class's __dict__ attribute to find the mangled name of the private attribute
class_dict = B.__dict__
#print(class_dict)
# The mangled name of the private attribute can be found in the class's dictionary
mangled_name = None
for key in class_dict:
    if key.startswith("_B__"):
        mangled_name = key
        break

print("Mangled name of the private attribute:", mangled_name)

#raise NotImplementedError()

Mangled name of the private attribute: None


In [23]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [ ]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object)) == True
print(isinstance(b, object)) == True
print(isinstance(a, B)) == False
print(isinstance(b, A)) == True
print(isinstance(d, A)) == True

In [ ]:
print(issubclass(C, object)) == True
print(issubclass(D, B)) == False
print(issubclass(B, D)) == False
print(issubclass(B, B)) == True

#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [24]:
class Animal:
    def __init__(self, name, age=0, number_of_legs=0):
        self.name = name
        self.age = age
        self.number_of_legs = number_of_legs

    def make_sound(self):
        pass

class Cat(Animal):
    def __init__(self, name, age=0, fur=None):
        super().__init__(name, age, number_of_legs=4)
        self.fur = fur
        self.make_sound()

    def make_sound(self):
        print(f"{self.name} the cat says 'Meow'")

class Dog(Animal):
    def __init__(self, name, age=0, fur=None):
        super().__init__(name, age, number_of_legs=4)
        self.fur = fur
        self.make_sound()

    def make_sound(self):
        print(f"{self.name} the dog says 'Woof'")

class Fish(Animal):
    def __init__(self, name, age=0, fur=None):
        super().__init__(name, age, number_of_legs=4)
        self.make_sound()
        
    def make_sound(self):
        print(f"{self.name} the fish makes no sound")

class Eagle(Animal):
    def __init__(self, name, age=0, fur=None):
        super().__init__(name, age, number_of_legs=4)
        self.make_sound()
        
    def make_sound(self):
        print(f"{self.name} the eagle makes a high-pitched sound")
        
#raise NotImplementedError()

In [25]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

Fluffy the cat says 'Meow'
Cherry the dog says 'Woof'
King the fish makes no sound
Bruce the eagle makes a high-pitched sound


#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [26]:
import numpy as np

def standardize(X):
    # Calculate the mean of each row
    row_means = np.mean(X, axis=1, keepdims=True)

    # Calculate the standard deviation of each column
    col_std = np.std(X, axis=0)

    # Standardize the array using broadcasting
    X_std = (X - row_means) / col_std

    return X_std
    raise NotImplementedError()

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [27]:
import numpy as np

def normalize(X):
    # Calculate the minimum and maximum values along each column
    X_min = np.min(X, axis=0)
    X_max = np.max(X, axis=0)

    # Normalize the array using broadcasting
    X_norm = (X - X_min) / (X_max - X_min)

    return X_norm
    raise NotImplementedError()

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0., 0., 1.],
       [1., 1., 0.]])

In [28]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)