In [1]:
grocery_list = ["tomatoes", "bananas", "onions", "milk", "eggs"]
print(grocery_list[2])

onions


In [5]:
full_name = "Gideon Mpungu"
print(full_name[4])

o


In [6]:
grocery_list = ["tomatoes", "bananas", "onions", "milk", "eggs"]
for item in grocery_list:
    print(item)

tomatoes
bananas
onions
milk
eggs


In [7]:
for num in range(11):
    squared = num ** 2
    print(squared)

0
1
4
9
16
25
36
49
64
81
100


In [9]:
import datetime as dt

time_now = dt.time(17, 25)
print(time_now)

17:25:00


In [14]:
import numpy as np

matrix = np.array([[1, 0], [0, 1]])
print(matrix)

[[1 0]
 [0 1]]


In [19]:
ones_array = np.ones((2, 3, 2))
print(ones_array)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [16]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = matrix[1, 2] 
print(element)

6


In [17]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Shape:", matrix.shape)
for row in matrix:
    for element in row:
        print(element)

Shape: (3, 3)
1
2
3
4
5
6
7
8
9


In [18]:
squared_matrix = np.square(matrix)
max_value = squared_matrix.max()
print("Maximum value:", max_value)

Maximum value: 81
